import React,{useCallback,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ConvexProvider,ConvexReactClient,useMutation,useQuery} from 'convex/react';
import {QRCodeSVG} from 'qrcode.react';
import {api} from './api';
import type {Command,View} from './engine';
import './style.css';
import {Narrator,ResultBanner,Scoreboard} from './Presentation';
function session() {
 let token=localStorage.getItem('partyroom-session');
 if(!token){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');localStorage.setItem('partyroom-session',token);}
 return token;
}
function Brand(){return <a className="brand" href="/">partyroom<span>✳</span></a>}
function Frame({children}:{children:React.ReactNode}){return <><header><Brand/><span className="tag">GOOD COMPANY. BAD ANSWERS.</span></header>{children}<footer>Made for the people in the room. <span>Volume up. Phones out.</span></footer></>}
function Setup(){return <Frame><main className="setup"><span className="eyebrow">DEVELOPER SETUP</span><h1>The party starts<br/>with a connection.</h1><p>This build needs a Convex backend before phones can join a shared room.</p><ol><li>Run <code>npx convex dev</code> in the project.</li><li>Set <code>VITE_CONVEX_URL</code> in your local environment or Vercel.</li><li>Restart the app or redeploy.</li></ol><p>Setup instructions and the deployment checklist are in the repository README.</p></main></Frame>}
class Boundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<Frame><main><h1>Let’s reconnect.</h1><p>Your room may have expired, or this browser does not have its session.</p><a className="button" href="/">Back to joining</a></main></Frame>:this.props.children}}
function App(){
 const [token]=useState(session),[code,setCode]=useState(()=>new URLSearchParams(location.search).get('room')??''),[active,setActive]=useState(()=>new URLSearchParams(location.search).get('resume')==='1');
 const [name,setName]=useState(()=>localStorage.getItem('partyroom-name')??''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const create=useMutation(api.create),join=useMutation(api.join),act=useMutation(api.act);
 const room=useQuery(api.view,active?{code,token}:'skip');
 const [connected,setConnected]=useState(true);
 useEffect(()=>{const update=()=>setConnected(navigator.onLine);addEventListener('online',update);addEventListener('offline',update);update();return()=>{removeEventListener('online',update);removeEventListener('offline',update)}},[]);
 async function run(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Please try again.')}finally{setBusy(false)}}
 function enter(c:string){setCode(c);setActive(true);history.replaceState(null,'',`/?room=${c}&resume=1`)}
 const saveDraft=useCallback(async(command:Extract<Command,{type:'draft'}>)=>{if(room)await act({code,token,epoch:room.epoch,command});},[act,code,token,room?.epoch]);
 function send(command:Exclude<Command,{type:'join'}>){if(room)void run(()=>act({code,token,epoch:room.epoch,command}));}
 return <Frame>{!connected&&<div className="notice" role="status">You’re offline. Your seat is saved—reconnecting when the network returns.</div>}{error&&<div className="notice error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error">×</button></div>}
 {!active?<main><section className="hero"><div><span className="eyebrow">YOUR LIVING ROOM. OUR GAME SHOW.</span><h1>Make a night<br/>of <em>bad ideas.</em></h1><p>One big screen. A few good friends.<br/>Absolutely no talent required.</p><button className="primary" disabled={busy} onClick={()=>void run(async()=>enter(await create({token})))}>Host a night <span>↗</span></button><small>3–8 players · Use your phones · No accounts</small></div><form className="join" onSubmit={e=>{e.preventDefault();void run(async()=>{localStorage.setItem('partyroom-name',name);enter(await join({code:code.toUpperCase(),token,name}))})}}><span className="eyebrow">GOT AN INVITE?</span><h2>You’re on the list.</h2><label>Room code<input autoCapitalize="characters" value={code} maxLength={5} placeholder="ABCDE" required onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/></label><label>Your name<input value={name} maxLength={24} placeholder="The funny one" required onChange={e=>setName(e.target.value)}/></label><button disabled={busy} className="dark">Join the room →</button></form></section><div className="section-title"><h2>The lineup</h2><span>THREE WAYS TO RUIN A FRIENDSHIP, NICELY.</span></div><section className="games"><article className="game lime"><span>01 / COMEDY</span><h2>Punchline</h2><p>Your worst answer.<br/>Their favorite joke.</p><b>FIRST PLAYABLE BUILD</b></article><article className="game pink"><span>02 / JOKE WRITING</span><h2>Ship<br/>Happens</h2><p>Write jokes. Sink gracefully.</p><b>COMING NEXT</b></article><article className="game violet"><span>03 / HORROR TRIVIA</span><h2>Last Call</h2><p>Know your stuff.<br/>Stay for the afterlife.</p><b>IN DEVELOPMENT</b></article></section></main>
 :room===undefined?<main><h1>Finding your people…</h1></main>:room===null?<main><h1>This room has closed.</h1><a className="button" href="/">Start another night</a></main>:<main className={room.isHost?'host':'controller'}><div className="room-title"><div><span className="eyebrow">PUNCHLINE / {room.phase==='lobby'?'THE GREEN ROOM':`ROUND ${room.round} OF ${room.rounds}`}</span><h1>{room.phase==='lobby'?'Everybody in.':room.phase==='writing'?'Make it ridiculous.':room.phase==='finished'?'Take a bow.':room.phase==='roundResults'?'That’s a wrap.':room.phase==='results'?'The room has spoken.':'And the answers are…'}</h1></div><div className="room-code"><span>ROOM</span><strong>{code}</strong></div></div>
 <Narrator room={room}/><Timer room={room}/>
 {room.phase==='lobby'?<section className="lobby"><div className="panel"><h2>The guest list <span>{room.players.length}/8</span></h2><ul className="players">{room.players.map((p,i)=><li key={p.id}><span className="avatar">{i+1}</span><b>{p.name}</b><span>{p.ready?'✓ Ready':'Getting settled'}</span>{room.isHost&&<button aria-label={`Remove ${p.name}`} onClick={()=>send({type:'remove',playerId:p.id})}>×</button>}</li>)}</ul>{!room.players.length&&<p className="empty">The best jokes haven’t arrived yet.<br/>Share the code to get everyone in.</p>}
 {room.me?<button className="primary" disabled={busy} onClick={()=>send({type:'ready',ready:!room.players.find(p=>p.id===room.me)?.ready})}>{room.players.find(p=>p.id===room.me)?.ready?'Actually, give me a second':'I’m ready →'}</button>:room.isHost?<form onSubmit={e=>{e.preventDefault();void run(()=>join({code,token,name}))}}><label>Play along as host<input value={name} required maxLength={24} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><button disabled={busy}>Take a seat</button></form>:null}</div>
 {room.isHost&&<aside className="panel invite"><QRCodeSVG value={`${location.origin}/?room=${code}`} size={160} bgColor="#faf8f0"/><h2>Scan. Join. Be funny.</h2><p>Open this page on the TV.<br/>Players scan with their phones.</p><label>Time to write<select value={room.seconds} onChange={e=>send({type:'settings',seconds:Number(e.target.value),rounds:room.rounds})}>{[60,120,180,300].map(n=><option key={n} value={n}>{n/60} {n===60?'minute':'minutes'}</option>)}</select></label><label>Rounds<select value={room.rounds} onChange={e=>send({type:'settings',seconds:room.seconds,rounds:Number(e.target.value)})}>{[1,2,3].map(n=><option key={n}>{n}</option>)}</select></label><button className="primary" disabled={busy||room.players.length<3||!room.players.every(p=>p.ready)} onClick={()=>send({type:'start'})}>Start Punchline →</button><small>Everyone needs to be ready. Minimum 3 players.</small></aside>}</section>:null}
 {room.phase==='writing'&&<section><p className="progress-copy">{room.submitted} of {room.total} answers are in. Two prompts each. Make yours count.</p><div className="answers">{room.tasks.map(t=><Answer key={`${room.round}-${t.index}`} task={t} room={code} busy={busy||room.remaining!==null} send={send} saveDraft={saveDraft}/>)}</div>{!room.me&&<div className="waiting"><h2>Great nonsense takes time.</h2><p>Write on your phones. The reveal happens here.</p><progress max={room.total} value={room.submitted}/></div>}</section>}
 {room.matchup&&<section className="matchup" key={`${room.round}-${room.matchup.index}`}><span className="eyebrow">MATCHUP {room.matchup.index+1} / {room.matchup.total}</span><h2 className="prompt-reveal">{room.matchup.prompt}</h2>
 <div className="answers">{room.matchup.answers.map((a,i)=>{
 const points=room.matchup?.result?.points??{};
 const winner=room.matchup?.result?.winners.some(id=>room.players.find(p=>p.id===id)?.name===a.author);
 return <div key={a.choice} className={`answer-slot ${a.revealed?'is-revealed':''}`}>
 {a.revealed?<button className={`answer-card ${i?'pink':'lime'} ${winner&&room.phase==='results'?'winning-answer':''} ${room.matchup?.result?.kind==='tie'?'tied-answer':''}`} disabled={busy||room.phase!=='voting'||!room.matchup?.canVote||room.matchup.voted||room.remaining!==null||!a.text} onClick={()=>send({type:'vote',choice:a.choice})}><span>ANSWER {i?'B':'A'}</span><strong>{a.text??'No answer submitted'}</strong>{room.phase==='results'&&<div className="answer-result"><b>{a.author}</b><span>{a.votes} {a.votes===1?'vote':'votes'}</span><strong>{Object.entries(points).find(([id])=>room.players.find(p=>p.id===id)?.name===a.author)?.[1]??0} pts</strong></div>}</button>:<div className="answer-placeholder"><span>ANSWER {i?'B':'A'}</span><strong>Coming up…</strong></div>}
 </div>;
 })}</div>
 {room.phase==='reveal'&&<p className="progress-copy" role="status">{room.revealStep===0?'First, the prompt…':room.revealStep===1?'Now, answer A…':'And answer B… Voting opens automatically.'}</p>}
 {room.phase==='voting'&&<><p className="progress-copy">{room.matchup.voted?'Vote locked in.':room.matchup.canVote?'Tap your favorite answer.':'Enjoy the vote—this matchup is yours.'} {room.matchup.voteCount}/{room.matchup.eligible} votes in.</p>{room.matchup.canVote&&<button className="reject-vote" disabled={busy||room.matchup.voted||room.remaining!==null} onClick={()=>send({type:'vote',choice:'both'})}>Both suck ✕</button>}<small>A strict majority of eligible voters choosing “Both suck” takes 100 points from each author.</small></>}
 {room.phase==='results'&&<ResultBanner room={room}/>}
 </section>}
 {['results','roundResults','finished'].includes(room.phase)&&<Scoreboard room={room}/>}
 {room.isHost&&room.phase!=='lobby'&&<nav className="host-controls" aria-label="Host controls">{room.deadline!==null&&<button disabled={busy} onClick={()=>send({type:'pause'})}>Pause</button>}{room.remaining!==null&&<button disabled={busy} onClick={()=>send({type:'resume'})}>Resume</button>}{(room.deadline!==null||room.remaining!==null)&&<button disabled={busy} onClick={()=>send({type:'extend'})}>+30 seconds</button>}{['results','roundResults'].includes(room.phase)&&<button className="primary" disabled={busy} onClick={()=>send({type:'next'})}>{room.phase==='roundResults'?(room.round<room.rounds?'Next round →':'Final results →'):room.matchup&&room.matchup.index+1===room.matchup.total?'Round results →':'Next matchup →'}</button>}{room.phase==='finished'&&<button className="primary" disabled={busy} onClick={()=>send({type:'lobby'})}>Back to the lobby →</button>}<button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen?.().catch(()=>{});}}>Fullscreen</button></nav>}
 </main>}</Frame>
}
function Timer({room}:{room:View}){const [now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),250);return()=>clearInterval(id)},[]);if((room.deadline===null&&room.remaining===null)||room.phase==='reveal')return null;const seconds=Math.max(0,Math.ceil((room.remaining??((room.deadline??now)-now))/1000));return <div className={`timer ${seconds<=15?'urgent':''}`} role="timer"><strong>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</strong><span>{room.remaining!==null?'PAUSED':'ON THE CLOCK'}</span></div>}
function Answer({task,room,busy,send,saveDraft}:{task:View['tasks'][number];room:string;busy:boolean;send:(c:Exclude<Command,{type:'join'}>)=>void;saveDraft:(c:Extract<Command,{type:'draft'}>)=>Promise<void>}){
 const key=`draft-${room}-${task.index}-${task.prompt}`;
 const [text,setText]=useState(()=>task.draft||sessionStorage.getItem(key)||'');
 const [status,setStatus]=useState('Saved drafts auto-submit when time runs out.');
 const revision=useRef(Math.max(task.revision,Date.now()*1000));
 const dirty=useRef(text!==task.draft);
 useEffect(()=>{
  if(!dirty.current||busy||task.answer!==null)return;
  let stopped=false,timer:ReturnType<typeof setTimeout>;
  const command:Extract<Command,{type:'draft'}>={type:'draft',match:task.index,text,revision:++revision.current};
  async function save(){
   try{await saveDraft(command);if(!stopped){dirty.current=false;setStatus('Saved · Auto-submits at timeout');}}
   catch{if(!stopped){setStatus('Not saved yet · Keep this screen open');timer=setTimeout(save,1500);}}
  }
  timer=setTimeout(save,250);return()=>{stopped=true;clearTimeout(timer);};
 },[text,busy,task.answer,task.index,saveDraft]);
 return <form className="panel writing-card" onSubmit={e=>{e.preventDefault();send({type:'answer',match:task.index,text})}}><h2>{task.prompt}</h2>{task.answer!==null?<div className="submitted"><p>{task.answer}</p><b>✓ Locked in. Beautifully questionable.</b></div>:<><label className="sr-only" htmlFor={`answer-${task.index}`}>Your answer</label><textarea id={`answer-${task.index}`} disabled={busy} maxLength={200} value={text} onChange={e=>{dirty.current=true;setText(e.target.value);setStatus('Saving…');sessionStorage.setItem(key,e.target.value)}} placeholder="Your moment of questionable genius…"/><small role="status">{status}</small><div className="form-bottom"><span>{text.length}/200</span><button className="primary" disabled={busy||!text.trim()}>Lock it in →</button></div></>}</form>;
}
const url=import.meta.env.VITE_CONVEX_URL;
createRoot(document.getElementById('root')!).render(<React.StrictMode><Boundary>{url?<ConvexProvider client={new ConvexReactClient(url)}><App/></ConvexProvider>:<Setup/>}</Boundary></React.StrictMode>);
