// Original Punchline prompts. Keep existing text stable: it identifies played prompts.
const original = [
 'The worst slogan for a luxury hotel on the moon.',
 'An absolutely unnecessary feature on a smart toaster.',
 'The one thing you should never put on a wedding invitation.',
 'A suspiciously specific rule at your new gym.',
 'The least convincing excuse for arriving three hours early.',
 'A terrible name for a very expensive candle.',
 'The first complaint in a restaurant run by raccoons.',
 'A motivational quote that would get you fired.',
 'Something a haunted fridge would whisper at midnight.',
 'The title of a reality show about your group chat.',
 'An alarming notification from your houseplants.',
 'The worst possible prize for winning a talent show.',
 'A rejected Olympic event that you would absolutely win.',
 'The real reason your printer refuses to cooperate.',
 'The most awkward thing a fortune cookie could predict.',
 'An unexpected item on a billionaire’s grocery list.',
 'A warning label that should come with adulthood.',
 'The least useful superpower at a dinner party.',
 'The password a pirate keeps forgetting.',
 'An apology that somehow makes everything worse.',
 'A terrible opening line for a museum audio guide.',
 'The secret ingredient in the world’s worst energy drink.',
 'Something you do not want your dentist to announce.',
 'The slogan for a vacation you will definitely regret.',
];
export const prompts = [...original,
 "The first rule of a fight club for extremely polite people.",
 "A terrible thing to hear from your GPS during a first date.",
 "The name of a dating app exclusively for ghosts.",
 "What your dog would put in your annual performance review.",
 "A suspicious item on a babysitter’s invoice.",
 "The worst way to announce that you got promoted.",
 "The hidden downside of being able to talk to furniture.",
 "A restaurant special that sounds like a legal threat.",
 "The final stage of becoming your parents.",
 "A bad slogan for a company that rents out grandmas.",
 "The title of your autobiography, according to your browser history.",
 "An unusual thing to shout during a very quiet yoga class.",
 "The worst souvenir to bring home from a submarine tour.",
 "The real purpose of the tiny pocket in your jeans.",
 "A terrible reason to request a refund on a wedding cake.",
 "What a pigeon says before doing something incredibly brave.",
 "The most embarrassing thing for a wizard to pull out of a hat.",
 "The reason aliens immediately locked their spaceship doors.",
 "The worst place to install a revolving door.",
 "A sentence that ruins any romantic candlelit dinner.",
 "The name of a superhero whose only power is mild inconvenience.",
 "What the self-checkout machine is really judging you for.",
 "An unexpected category at the World’s Pettiest Awards.",
 "The catchphrase of a deeply unqualified detective.",
 "An honest slogan for airport sandwiches.",
 "The first thing a clone of you would complain about.",
 "The worst message to find inside a bottle washed ashore.",
 "A job that should absolutely not have a bring-your-kid day.",
 "The name of a luxury perfume that smells like Monday.",
 "A sign you hired the wrong exorcist.",
 "The most useless thing to pack for a deserted island.",
 "What a secret society of librarians is plotting.",
 "A terrible name for a cruise ship’s emergency exit.",
 "The actual reason dinosaurs went extinct.",
 "A deeply unimpressive world record you could break tonight.",
 "What your phone would say if it could file for divorce.",
 "A suspicious perk in a job listing for a castle guard.",
 "The opening sentence of the worst best-man speech.",
 "A warning you never want to hear at an all-you-can-eat buffet.",
 "The secret sixth love language.",
 "An event that would make competitive napping exciting.",
 "The least intimidating name for a motorcycle gang.",
 "A terrible business to open inside an elevator.",
 "What a snowman puts on a dating profile.",
 "A rejected flavor of toothpaste for adults.",
 "The first thing you’d outlaw as mayor of your couch.",
 "The real reason the Wi-Fi is slow at a haunted hotel.",
 "A very bad thing to add to a treasure map.",
 "The name of a support group for people who clap when planes land.",
 "What a robot would consider a midlife crisis.",
 "A terrible replacement for the school bell.",
 "The most passive-aggressive thing a smart speaker could say.",
 "The biggest scandal at a competitive knitting tournament.",
 "A new national holiday that everyone would actually celebrate.",
 "The least reassuring thing a pilot could say over the intercom.",
 "An extremely specific reason to get banned from a petting zoo.",
 "A slogan for a gym where nobody wants to exercise.",
 "The bonus feature on the world’s most expensive spoon.",
 "A line that definitely wasn’t in the original fairy tale.",
 "The first sign your therapist is actually three raccoons.",
 "What a volcano would complain about in an online review.",
 "A disappointing discovery at the end of a rainbow.",
 "The worst possible name for a password manager.",
 "A terrible phrase to embroider on a throw pillow.",
 "The real reason your missing socks never return.",
 "The title of a cooking show hosted by a fire alarm.",
 "A rule that would instantly improve meetings.",
 "The least useful thing a time traveler could warn you about.",
 "A secret menu item at a restaurant for villains.",
 "The slogan on a very disappointing magic carpet.",
 "The text you really don’t want from your house sitter.",
 "The only acceptable reason to wear a cape to a tax appointment.",
 "An unexpected item in a survival kit for family dinners.",
 "What a hamster thinks happens outside its cage.",
 "The most unnecessary thing to make Bluetooth-enabled.",
 "A very awkward name for a couples’ massage package.",
 "The reason a ghost got fired from a haunted house.",
 "A terrible thing to put on a lost-pet poster.",
 "The biggest problem with a bank run by pirates.",
 "A warning label for your group chat.",
 "An activity that becomes sinister when called a team-building exercise.",
 "What your fridge would list as your greatest achievement.",
 "The worst theme for a children’s birthday party magician.",
 "An unexpected qualification for becoming king.",
 "The name of a theme park for people who hate surprises.",
 "The first review of a hotel built inside a whale.",
 "A terrible line for a motivational fitness instructor.",
 "What a dragon hoards after getting bored of gold.",
 "The first sign your new roommate is a retired supervillain.",
 "An honest name for the drawer full of random cables.",
 "A question that should never appear on a job interview form.",
 "The most disappointing thing to inherit from a mysterious uncle.",
 "The title of a horror movie about assembling flat-pack furniture.",
 "The slogan for a dating service run by your mom.",
 "The secret ingredient in a potion of mild disappointment.",
 "A suspicious announcement at the neighborhood barbecue.",
 "The least impressive way to escape from prison in a movie.",
 "What an octopus would do with a smartwatch.",
 "An unsettling name for an airline’s loyalty program.",
 "The thing you should never say while cutting someone’s hair.",
 "The first rule at a finishing school for trolls.",
 "A terrible name for a meditation app.",
 "The sound your wallet would make if it could scream.",
 "A sport that definitely shouldn’t be played in an office.",
 "The reason a mermaid failed her driving test.",
 "A suspicious extra fee on a hotel bill.",
 "The most embarrassing thing to accidentally project onto a meeting screen.",
 "A slogan for a coffee shop that has completely given up.",
 "The worst possible update to a doorbell.",
 "A sentence that makes any recipe sound dangerous.",
 "What a gargoyle does on its day off.",
 "The most useless advice a fortune teller could give.",
 "A new museum exhibit nobody asked for.",
 "The name of a reality show about people sharing one charger.",
 "The worst thing to write in the comments section of a wedding RSVP.",
 "What a superhero calls in sick with.",
 "The real reason the moon only comes out at night.",
 "A terrible name for a high-end seafood restaurant.",
 "The warning your future self would leave on your bathroom mirror.",
 "A rejected feature of the next generation of humans.",
 "The first purchase of a raccoon who wins the lottery.",
 "A sentence you don’t want to hear in an escape room.",
 "The slogan for a terrible house-cleaning service.",
 "An unexpected thing to find in the office suggestion box.",
 "The one thing a vampire cannot resist at the grocery store.",
 "A new use for the extra buttons on a TV remote.",
 "The real meaning of “some assembly required.”",
 "A very questionable name for a daycare newsletter.",
 "The biggest problem with a restaurant that serves only soup.",
 "What the little man inside a traffic light does on red.",
 "An honest slogan for a storage unit company.",
 "A reason your evil twin wants to switch back.",
 "The award you’d win at a ceremony for ordinary household tasks.",
 "A terrible thing for a tour guide to say before turning off the lights.",
 "The name of a spa treatment invented by a plumber.",
 "The worst possible suggestion from an autocomplete keyboard.",
 "The secret handshake at a club for people with too many tabs open.",
 "An unexpected new feature of a shopping cart.",
 "The title of a romance novel set entirely in a hardware store.",
 "What an alien mistakes for Earth’s most sacred tradition.",
 "The most awkward thing a parrot could repeat at a dinner party.",
 "A bad reason to ring the emergency bell on a train.",
 "The name of a very budget-friendly space program.",
 "The fine print on a genie’s three-wishes contract.",
 "A terrible alternative to throwing rice at weddings.",
 "The most suspicious item at a church bake sale.",
 "A message you never want to see on a hotel TV.",
 "What a skeleton worries about before a first date.",
 "A terrible name for a neighborhood watch group.",
 "The real reason nobody reads the terms and conditions.",
 "An unexpected skill on a ninja’s résumé.",
 "The slogan for an app that makes your life slightly worse.",
 "A terrible icebreaker for a room full of strangers.",
 "What a very lazy villain threatens to do to the world.",
 "The worst excuse for missing your own surprise party.",
 "A rejected safety announcement for a roller coaster.",
 "The thing that finally made the tooth fairy unionize.",
 "A weird flex to put on a business card.",
 "The name of a shampoo marketed to werewolves.",
 "What a cat would charge you rent for.",
 "A terrifying sentence that begins with “Good news!”",
 "The reason a wizard got banned from a farmers’ market.",
 "The title of a documentary about the office microwave.",
 "An unexpected item on a very small bucket list.",
 "The motto of a secret club for terrible dancers.",
 "The worst time for a confetti cannon to go off.",
 "A suspicious instruction in a hotel’s welcome booklet.",
 "The name of an energy drink designed for people doing nothing.",
 "What a knight writes in a resignation letter.",
 "A horrible slogan for a meal-prep service.",
 "The strangest thing to discover your neighbor is collecting.",
 "The first thing a talking mirror would ask you to stop doing.",
 "A completely unnecessary upgrade to a bathrobe.",
 "The excuse a superhero gives for saving the wrong city.",
 "A disappointing answer to “What’s behind door number three?”",
 "The name of a podcast hosted by your two remaining brain cells.",
];
